apiVersion: v1
kind: Service
metadata:
  name: app-nodeport
spec:
  selector:
    app: app-test
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30077
  type: NodePort
