apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
        - name: app-test
          image: hajarnaityahia973/app-test:latest
          ports:
            - containerPort: 8084
