apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
  namespace: webappps
spec:
  selector:
    matchLabels:
      app: app-back
  replicas: 2
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
        - name: app-back
          image: hajarnaityahia973/app-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: app-back
  namespace: webappps
spec:
  selector:
    app: app-back
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8084
      nodePort: 30009
  type: NodePort
