apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: app-back
spec:
  selector:
    matchLabels:
      app: app-back
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
        - name: app-back
          image: hajarnaityahia973/app-back:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8084 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: app-back
spec:
  selector:
    app: app-back
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8084
      nodePort: 30008 # Vous pouvez choisir un port dans la plage 30000-32767
  type: NodePort
