// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test23Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test23() {
    driver.get("http://localhost:8066/indexPatient");
    driver.manage().window().setSize(new Dimension(1292, 702));
    driver.findElement(By.cssSelector(".card-header")).click();
    driver.findElement(By.linkText("Supprimer")).click();
    assertThat(driver.switchTo().alert().getText(), is("êtes-vous sûr ?"));
    driver.switchTo().alert().accept();
    {
      WebElement element = driver.findElement(By.linkText("Meds"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Meds"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Meds"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Meds")).click();
    driver.findElement(By.linkText("New")).click();
    driver.findElement(By.name("nom")).click();
    driver.findElement(By.linkText("Meds")).click();
    driver.findElement(By.linkText("List")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("selenium-ide-indicator"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".sb-nav-fixed")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn-danger")).click();
    assertThat(driver.switchTo().alert().getText(), is("etes vous sure?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn-danger")).click();
    assertThat(driver.switchTo().alert().getText(), is("etes vous sure?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn-primary")).click();
    driver.findElement(By.name("nom")).click();
    driver.findElement(By.name("nom")).sendKeys("merieM A2ZS");
    driver.findElement(By.name("age")).click();
    driver.findElement(By.name("age")).sendKeys("29");
    driver.findElement(By.cssSelector(".btn-dark")).click();
    driver.findElement(By.name("keyword")).click();
    driver.findElement(By.cssSelector(".card-body")).click();
    driver.findElement(By.name("keyword")).click();
    driver.findElement(By.name("keyword")).sendKeys("Mer");
    driver.findElement(By.cssSelector(".btn-outline-secondary")).click();
  }
}
